### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Raz92** [KevinLage/Edu-Account-creator#81]
View Bot not working please update

**Comment by Raz92** [comment]
WHY U Not Reply Brother

**Comment by 0m3rta13** [comment]
> WHY U Not Reply Brother

Dude. You're actually being extremely disrespectful right now and I'm going to have to ask that you please stop it. 

Firstly, you're opening these issues on an entirely different project which, on its own is out of bounds.

Secondly, the project you're obsessively asking about has been archived (which I assume is why you're spamming here) so there is no development happening with it. It's been over a year since it was worked on so at this point so much has changed it would probably require a total rewrite.

So please. Show @KevinLage some respect for the work he has done and instead of creating an environment that ends up being one of the many reasons a lot of devs just give up on the community and stop contributing entirely.

You have no idea what is going on in other people's lives so assuming he even has the time to work on stuff is rather naive and immature. 
He might also simply not want to and hey, that's perfectly fine too.

It's his time. It's his choice. So please, stop with the nagging and respect that. 

Thank you.

**Comment by supersri811** [comment]
Ya, Show the guy some respect dude.
He's worked on it for hours.
